### ISSUE TITLE
Translation fehlt

### ISSUE THREAD

**Issue by hai0mi** [LuxJakob/supplyChainSimulation#2]

**Comment by goodfel10w** [comment]
> Als Gegenvorschlag:
> 
> Man muss sich auch nicht so sehr verkünsteln. Man kann am Anfang über ein ComboBox Menü (1 - english; 2 - deutsch) die Sprache auswählen lassen, und diese in SharedData als 'public static int languageIndex;' speichern. Und danach auf jeder Seite unter 'InitializeComponent();' sagen: if (languageIndex == 2) { labelDeinerWahl.Text = "dein deutscher Text"; }
> 
> Aber - neuer Ansatz bitte in nem neuen Branch!!

Combobox mit Dropdown ist eingebaut. 
Die Anwendung wird dann auf Englisch oder Deutsch gesetzt und holt sich die Übersetzungen aus dem Ressource Files. Ist dann gar nicht mehr schwer und leichter als es im Code mit if checks abzubilden.
