### ISSUE TITLE
Aufträge in Bearbeitung bei der Materialplanung zu hoch

### ISSUE THREAD

**Issue by LuxJakob** [LuxJakob/supplyChainSimulation#45]

**Comment by goodfel10w** [comment]
Order in Queue -> Zahl ist zu hoch weil in der XML
Erstes Element pro Workstation ist **inBEARBEITUNG** d.h. jedes weitere Element ist **IN WARTESCHLANGE**.

Aufsummieren aller ITEMS die in Warteschlange sind.

**Comment by goodfel10w** [comment]
Im branch 44 liegt mein aktueller Lösungsversuch
